#-----------------------------
# Optimizer section args (KerasFL-compatible SGD)
#-----------------------------
optimizer:
  type: SGD
  lr: 0.1
  weight_decay: 0.0
  momentum: 0.0
  nesterov: False
  betas: [0.9, 0.999]
  amsgrad: False
  eps: 1e-8
  alpha: None
  centered: None
